config/routes.rb
Lecture2::Application.routes.draw do

  get "home" => "page#home"
  get "about_us" => "page#about_us"
  match "contact_us" => "page#contact_us", :via => [:post, :get]
  get "products" => "page#products"
  get "newsletter" => "page#newsletter"
  get "blog" => "page#about_us"
  get "calendar(/:year(/:month))" => "page#calendar", :as => 'calendar'
  get "articles" => "page#articles"
  get "login" => "page#login"

  get "say/hello"
  get "say/goodbye"
  get "say/something"

  root "page#home"

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dwight_controller.rb
class DwightController < ApplicationController
  def teach
  end

  def speak
  end

  def dig
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def about_us
  end

  def contact_us
    @name = params["name"]
      if @name == ""
        @error_msg = "Please Enter Name"
      end
    @email = params["email"]
  end

  def products
  end

  def newsletter
  end

  def blog
  end

  def calendar
    @time = Time.now
    @month = params['month'].to_i
    @year = params['year'].to_i
    if( !(@month >= 1 && @month <= 12) )
      @month = @time.strftime("%m").to_i
    end
    if (@year <= 0)
      @year = @time.strftime("%Y").to_i
    end
  end

  def articles
  end

  def login
  end
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @yo = "Yo Ho!"
    @now = Time.now
  end

  def goodbye

  end

  def something

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link_to( click_text, action, url, style )
    if action_name == action
      return link_to click_text, url, :class => style
    else
      return link_to click_text, url
    end
  end


end

app/helpers/dwight_helper.rb
module DwightHelper
end

app/helpers/page_helper.rb
module PageHelper

  def calendar( month, year )
    current_date = Date.new(year,month)

    prev_month = month - 1
    prev_year = year
    if( prev_month <= 0 )
      prev_month = 12
      prev_year = year - 1
    end

    next_month = month + 1
    next_year = year
    if( next_month >= 13 )
      next_month = 1
      next_year = year + 1
    end
    cal = "" #"/calendar/#{prev_year}/#{prev_month}"
    cal += link_to "Prev", calendar_path(:month=>prev_month, :year=>prev_year)
    cal += link_to "Next", calendar_path(:month=>next_month, :year=>next_year)
    cal += current_date.strftime("%B")
    day_of_week = current_date.strftime("%w").to_i
    cal += "<table border='1'>\n\t<tr>\n"
    days = %w(Sun Mon Tue Wed Thu Fri Sat)
    days.each do | day |
      cal += "\t\t<td>#{day}</td>\n"
    end

    #second row - first week of the month
    cal += "<tr>"
    day_of_week.times do
      cal += "<td>&nbsp;</td>"
    end

    #print the days of week starting with 1
    (7 - day_of_week).times do |day|
      cal += "<td>#{day + 1}</td>"
    end

    cal += "</tr>"

    cal += "</tr>\n</table>\n"
    cal += "Month: #{month}<br />Year: #{year}<br />"
    cal += day_of_week.to_s
    return cal
  end
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/dwight/dig.html.erb
<h1>Dwight#dig</h1>
<p>Find me in app/views/dwight/dig.html.erb</p>

app/views/dwight/speak.html.erb
<h1>Dwight#speak</h1>
<p>Find me in app/views/dwight/speak.html.erb</p>

app/views/dwight/teach.html.erb
<h1>Dwight#teach</h1>
<p>Find me in app/views/dwight/teach.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Lecture</title>
  <%= stylesheet_link_tag    "application", media: "screen", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body>
<div id="wrapper" class="col_100.wrap"><!-- #wrapper -->

  <header class="col_100.wrap"><!-- header -->
    <h1 class="col_100 logo">Cowboy Up</h1>
    <h2 class="col_100 center">Where the buffalo roam</h2>
    <br>
    <%= image_tag "cowboyup.jpg", :class => "col_100", :alt => "Dave's a Cowboy" %><!-- header image -->
  </header><!-- end of header -->

  <%= render :partial => 'shared/nav', :class => 'col_100' %>

  <section id="main" class="col_100.wrap"><!-- #main content and sidebar area -->
    <section id="container"><!-- #container -->
      <section id="content" class="col_66 yield"><!-- #content -->
<%= yield %>
      </section><!-- end of #content -->
    </section><!-- end of #container -->

    <aside id="sidebar" class="col_33"><!-- sidebar -->
      <h3>Things To Do</h3>
      <ul>
        <li><a href="#">Play Games</a></li>
        <li><a href="#">Chat With Friends</a></li>
        <li><a href="#">Swap Stories</a></li>
        <li><a href="#">Sell Stuff</a></li>
        <li><a href="#">Buy Stuff</a></li>
        <li><a href="#">Trade Stuff</a></li>
      </ul>

      <h3>Our Sponsors</h3>
      <%= image_tag "ad125.jpg" %><%= image_tag "ad125.jpg" %><br />
      <%= image_tag "ad125.jpg" %><%= image_tag "ad125.jpg" %><br /><br />

      <h3>Connect With Us</h3>
      <ul>
        <li><a href="#">Twitter</a></li>
        <li><a href="#">Facebook</a></li>
      </ul>

    </aside><!-- end of sidebar -->

  </section><!-- end of #main content and sidebar-->

  <footer class="col_100 footer">
    <section id="">

      <section id="footer-outer-block">
        <aside id="first" class="col_25">
          <h3>Blogroll</h3>
          <ul>
            <li><a href="#">one linkylink</a></li>
            <li><a href="#">two linkylinks</a></li>
            <li><a href="#">three linkylinks</a></li>
            <li><a href="#">four linkylinks</a></li>
            <li><a href="#">five linkylinks</a></li>
          </ul>
        </aside><!-- end of #first footer segment -->

        <aside id="second" class="col_25">
          <h3>Awesome Stuff</h3>
          <ul>
            <li><a href="#">one linkylink</a></li>
            <li><a href="#">two linkylinks</a></li>
            <li><a href="#">three linkylinks</a></li>
            <li><a href="#">four linkylinks</a></li>
            <li><a href="#">five linkylinks</a></li>
          </ul>
        </aside><!-- end of #second footer segment -->

        <aside id="third" class="col_25">
          <h3>Coolness</h3>
          <ul>
            <li><a href="#">one linkylink</a></li>
            <li><a href="#">two linkylinks</a></li>
            <li><a href="#">three linkylinks</a></li>
            <li><a href="#">four linkylinks</a></li>
            <li><a href="#">five linkylinks</a></li>
          </ul>
        </aside><!-- end of #third footer segment -->

        <aside id="fourth" class="col_25">
          <h3>Blahdyblah</h3>
          <p>Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum.</p>
        </aside><!-- end of #fourth footer segment -->

      </section><!-- end of #footer-outer-block -->

    </section><!-- end of #footer-area -->
  </footer>

</div><!-- #wrapper -->
</body>
</html>

app/views/page/about_us.html.erb
<h1>Page#about_us</h1>
<p>Find me in app/views/page/about_us.html.erb</p>

app/views/page/articles.html.erb
<h1>Page#articles</h1>
<p>Find me in app/views/page/articles.html.erb</p>

app/views/page/blog.html.erb
<h1>Page#blog</h1>
<p>Find me in app/views/page/blog.html.erb</p>

app/views/page/calendar.html.erb
<h1>Calendar</h1>


<%= calendar(@month, @year).html_safe %>

app/views/page/contact_us.html.erb
<h1>Page#contact_us</h1>

<div class="warning">
  Your name is: <%= @name %><br>
  Your email is: <%= @email %>
</div>

<!--<pre>
<% params.each do |key, value| %>
    <%= key + " ==> " + value %>
<% end %>
</pre>-->

<%= @error_msg %>
<%= form_for contact_us_path, :mothod => "POST" do %>
    <%= label_tag :name, "Your Name:" %> <%= text_field_tag :name, @name %><br>
    <%= label_tag :email, "Your Email:" %> <%= email_field_tag :email, @email %><br>Your email is: <%= @email %><br>
    <%= submit_tag "Submit" %>
<% end %>

app/views/page/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>

app/views/page/login.html.erb
<h1>Page#login</h1>
<p>Find me in app/views/page/login.html.erb</p>

app/views/page/newsletter.html.erb
<h1>Page#newsletter</h1>
<p>Find me in app/views/page/newsletter.html.erb</p>

app/views/page/products.html.erb
<h1>Page#products</h1>
<p>Find me in app/views/page/products.html.erb</p>

app/views/say/goodbye.html.erb
<h1>Say#goodbye</h1>

app/views/say/hello.html.erb
<h1>Say#hello</h1>
<p>Find me in app/views/say/hello.html.erb</p>

<%= link_to "Dwight Teach", dwight_teach_path %>

app/views/say/something.html.erb
<h1>say#something</h1>

app/views/shared/_nav.html.erb
<nav><!-- top nav -->
  <div class="menu_main">
    <ul>
      <li><%= nav_link_to "Home", "home", home_path, "current_page" %></li>
      <li><%= nav_link_to "About Us", "about_us", about_us_path, "current_page" %></li>
      <li><%= nav_link_to "Contact Us", "contact_us", contact_us_path, "current_page" %></li>
      <li><%= nav_link_to "Products", "products", products_path, "current_page" %></li>
      <li><%= nav_link_to "Newsletter", "newsletter", newsletter_path, "current_page" %></li>
      <li><%= nav_link_to "Blog", "blog", blog_path, "current_page" %></li>
      <li><%= nav_link_to "Calendar", "calendar", calendar_path, "current_page" %></li>
      <li><%= nav_link_to "Articles", "articles", articles_path, "current_page" %></li>
      <li><%= nav_link_to "Login", "login", login_path, "current_page" %></li>
    </ul>


      <%#= nav_link_to "Products", "products", products_path, "current_page" %>
      <%#= nav_link_to "Articles", "articles", articles_path, "current_page" %>
      <%#= nav_link_to "Contact Us", "contact_us", contact_us_path, "current_page" %>
      <%#= nav_link_to "About Us", "about_us", about_us_path, "current_page" %>
      <%#= nav_link_to "Newsletter", "newsletter", newsletter_path, "current_page" %>
      <%#= nav_link_to "Calendar", "calendar", calendar_path, "current_page" %>
      <%#= nav_link_to "Blog", "blog", blog_path, "current_page" %>
      <%#= nav_link_to "Login", "login", login_path, "current_page" %>
  </div>
</nav><!-- end of top nav -->